# Site settings
title: Svatba
tag_text: Svatba
description: A responsive template for publishing single-page websites, articles that are easy on the eyes
url: "https://simekadam.github.io/svatba/"
baseurl: "https://simekadam.github.io/svatba/"

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
